### ISSUE TITLE
We need to expand the app fields to be a singular app in the applications object 

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#13]
https://github.com/hossted/cli/blob/ccaa5eb110509a3f5a900588c236178e75d1ddc1/hossted/templates/config.tmpl#L6

Something like this
```

mail: {{ .Email }}
organization: {{ .Organization }}
userToken: {{ .UserToken }}
sessionToken: {{ .SessionToken }}
uuidPath: /opt/linnovate/run/uuid.txt
applications:
    app1:
     appName: {{ .AppName}}
    appPath: {{ .AppPath}}
  app2: 
     appNAme:
     appPath
```

**Comment by billylkc** [comment]
Can you explain a little bit more on how does the multiple applications work. Cause right now, the app variable is getting from the file  (/opt/linnovate/run/software.txt), and the program is only checking the first line of the file.

Do you mean somehow we get it from somewhere else for the second or third applications name?

**Comment by billylkc** [comment]
And currently changes in the structure of the config file (like in this case, add one more level in yaml) needs to remove the old config manually.
No easy way to do the 'config upgrade' for now.

**Comment by billylkc** [comment]
and how do we know which app (app1 or app2) when calling hossted ps/hostted log?
Needs some kind of logic for me to look up which app (app1 or app2) without hard coding.

**Comment by billylkc** [comment]
Updated to support multiple applications.
Updated format for config.yaml

```
email: billy@hosstedcom
userToken:
sessionToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIzLCJpYXQiOjE2NDY4NDIxOTAsImV4cCI6MTY0NjkyODU5MH0.JMUCLFMHLznZ7Dc0uNFhFFS0J-LqoB_mAehnMFFwgfs
uuidPath: /opt/linnovate/run/uuid.txt
applications:
    - appName: wikijs
      appPath: /opt/wikijs
    - appName: demoapp
      appPath: /opt/demopp

```
