### ISSUE TITLE
Grafana agent mimir updates 

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#62]
Place holder issue for this message...
```
i just checked my previous config for grafana agent. I had manually specified which url to scrape configs from

      configs:
      - name: integrations
        remote_write:
        - url: http://mimir-nginx.mimir-test.svc:80/api/v1/push
        scrape_configs:
        - job_name: kube-state-metrics
          static_configs:
            - targets: ['kube-state-metrics.hossted-operator.svc:8080']   
```
@AdheipSingh : i'll try to see if i can make this dynamic without specifying manually. need to research on exact config.
